### ISSUE TITLE
About plot 

### ISSUE THREAD

**Issue by xuwanxing** [rujinwang/SCOPE#10]
Hi, there.
I'm trying to run SCOPE with mouse single cells (3 wild types and 3 knock-outs). 
Here is my R script:
[https://github.com/xuwanxing/Scripts/blob/main/SCOPE-rscript.r](url)
And the final plot:
![plot_iCN_demo](https://user-images.githubusercontent.com/75006906/142964290-624c5c7b-22ff-4a11-92c1-f5c1509eb738.png)
It's not a heatmap. Is there something wrong with my script? 
Could you please help me? Thanks.

**Comment by rujinwang** [comment]
Hi, 
Thanks for your interest in SCOPE. 
How many cells do you have? Only 3 normal cells and 3 non-diploid/cancer cells? Why do you think the heatmap is incorrect? How many cells are there in the plot you showed? 
Thanks. 

Best, 
Rujin

**Comment by xuwanxing** [comment]
> Hi, Thanks for your interest in SCOPE. How many cells do you have? Only 3 normal cells and 3 non-diploid/cancer cells? Why do you think the heatmap is incorrect? How many cells are there in the plot you showed? Thanks.
> 
> Best, Rujin

Sorry for unclear expression. I have 18 cells in total. Here I try to use 6 cells (3 controls and 3 cases) to run script. Maybe the number of the cells is too small?

**Comment by rujinwang** [comment]
Hi, 
Yeah, you could try to deposit all of your cells and run SCOPE. 18 cells in total won't take too long. But I still don't understand why you mentioned above that the heatmap is incorrect. 

Rujin

**Comment by xuwanxing** [comment]
> Hi, Yeah, you could try to deposit all of your cells and run SCOPE. 18 cells in total won't take too long. But I still don't understand why you mentioned above that the heatmap is incorrect.
> 
> Rujin

I mean the heatmap doesn't show obvious difference among cells. Sorry for using ambiguous words. I'll rerun SCOPE with all the cells and update the results later. Thanks a lot.

**Comment by xuwanxing** [comment]
Hi Rujin, 
Here is the new result, just like the above one.
![plot_iCN_demo](https://user-images.githubusercontent.com/75006906/143800661-5de79094-d8fd-42c7-a85b-a920186be2e2.png)
I don't know what's wrong. Could you please help me?

**Comment by rujinwang** [comment]
Hi, 
I don't know what you are expecting. But I felt like it's a fair heatmap indicating one distinct non-diploid cell cluster in addition to diploid cells. I guess your question is why the CNV profiles returned for all cancer cells are the same, right? SCOPE adopted cross-sample segmentation, which returns breakpoints that shared by cells from the same genetic background. I hope this could be helpful. Thanks. 

Best, 
Rujin

**Comment by xuwanxing** [comment]
> Hi, I don't know what you are expecting. But I felt like it's a fair heatmap indicating one distinct non-diploid cell cluster in addition to diploid cells. I guess your question is why the CNV profiles returned for all cancer cells are the same, right? SCOPE adopted cross-sample segmentation, which returns breakpoints that shared by cells from the same genetic background. I hope this could be helpful. Thanks.
> 
> Best, Rujin

Yeah. Because the cells are from different ages of mice, I'm expecting there might be different CNV profiles and subclusters.

**Comment by rujinwang** [comment]
I think you can try to plot the heatmap of Y/Yhat and check if there are different CNV profiles and/or subclusters. If not, no wonder that SCOPE returns homogeneous CNVs across all non-diploid cells.

**Comment by xuwanxing** [comment]
Hi Rujin,


I try to plot Y and Yhat.sim respectively. (see attached file)

I notice that they have some subclusters. Am I right? Could you please tell me what to do next? Thank you very much.


Best,

Wanxing

**Comment by rujinwang** [comment]
> Hi Rujin, I try to plot Y and Yhat.sim respectively. (see attached file) I notice that they have some subclusters. Am I right? Could you please tell me what to do next? Thank you very much. Best, Wanxing 发件人：Rujin Wang ***@***.***> 发送日期：2021-11-30 00:18:16 收件人：rujinwang/SCOPE ***@***.***> 抄送人：xuwanxing ***@***.***>,Author ***@***.***> 主题：Re: [rujinwang/SCOPE] About plot (Issue #10) I think you can try to plot the heatmap of Y/Yhat and check if there are different CNV profiles and/or subclusters. If not, no wonder that SCOPE returns homogeneous CNVs across all non-diploid cells. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Hi, 
I didn't find your attachment. Could you please send it to my email at rujin@email.unc.edu ? Thanks. 

Best,
Rujin

**Comment by xuwanxing** [comment]
Yes, sure. I've sent it to your email. Please find the attachment. Thanks.

**Comment by rujinwang** [comment]
Hi, 
I'm confused with your plot. What's the scale of your heatmap values? Why does the legend range from 1e+5 to 5e+5? It's incorrect. How did you observe there are subclusters? 
What I meant is that you can plot log(Y/Yhat), where positive values indicate potential amplifications and negatives are deletions. If there are indeed subclusters, you may observe a heatmap alike supplementary Figure S8 in our paper. I cannot tell anything solely from your heatmap. 

Best, 
Rujin

**Comment by xuwanxing** [comment]
Thanks. Because I just plot Y and Yhat.sim respectively using package "pheatmap". 
After reading these lines of the script, I think actually I can plot log(Y_sim/Yhat.sim).

for (chri in chrs) {
    message('\n', chri, '\n')
    segment_cs[[chri]] <- segment_CBScs(Y = Y_sim,
                                    Yhat = Yhat.sim,
                                    sampname = colnames(Y_sim),
                                    ref = ref_sim,
                                    chr = chri,
                                    mode = "integer", max.ns = 1)
}

So I run the following commands:

> test<-log(Y_sim/Yhat.sim)
> head(test)
                              cell1      cell2        cell3      cell4
chr1:51069091-51569090 -0.004045859 -0.8197798 -0.006282743 -0.7432411
chr1:51569091-52069090 -0.001606426 -0.5621189 -0.002306806 -0.3933211
chr1:52069091-52569090  0.000000000 -0.8873032  0.000000000 -0.4659751
chr1:56069091-56569090  0.000000000 -0.4998966  0.000000000 -0.7331525
chr1:82069091-82569090 -0.001638002 -0.6357261 -0.001902950 -0.7142747
chr1:87069091-87569090 -0.001673641 -0.5906075 -0.001885015 -0.7018809
                            cell5
chr1:51069091-51569090 -0.8270952
chr1:51569091-52069090 -0.6617137
chr1:52069091-52569090 -0.6188047
chr1:56069091-56569090 -0.5300428
chr1:82069091-82569090 -0.6500636
chr1:87069091-87569090 -0.7428768
> pheatmap(test,filename="heatmap.png")

Finally I get this heatmap. https://github.com/xuwanxing/Scripts/blob/main/heatmap.png
Can this plot tell meaningful information?

**Comment by rujinwang** [comment]
Hi, 
This heatmap returns a single cluster of three cancer cells visually, which is in agreement with your previous SCOPE segmented profiles. Thanks. 

Rujin
