### ISSUE TITLE
Nearly all samples were excluded in QC due to low proportion of mapped reads

### ISSUE THREAD

**Issue by yifnzhao** [rujinwang/SCOPE#12]
Hi Rujin,

I am interested in running SCOPE for my low-coverage (0.01-0.1x) single-cell data. I encountered the following error when running SCOPE on my ~100 cell data:

```
Removed 0 samples due to failed library preparation.
Removed 6 samples due to failure to meet min coverage requirement.
Removed 94 samples due to low proportion of mapped reads.
Excluded 371 bins due to extreme GC content.
Excluded 357 bins due to low mappability.
Error in apply(apply(Y.nonzero, 2, function(x) { :
  dim(X) must have a positive length
Calls: perform_qc -> apply
Execution halted
```

Nearly all samples were excluded due to "low proportion of mapped reads". Note that prior to running SCOPE, all PCR duplicates were removed.

Therefore, I would like to seek your advice on 1) whether SCOPE is suitable for this type of application (copy number detection in ultra-low-coverage scWGS data); 2) and if so, which parameter(s) in SCOPE pipeline could be tuned to relax the QC threshold and what the caveats are.

Thanks in advance!

Yifan

**Comment by rujinwang** [comment]
Hi @yifnzhao, 
Thanks for your interest in SCOPE. 1) SCOPE is well applied to low-coverage scWGS. 2) You can adjust parameter `mapq20_thresh` in the function `perform_qc()`, which is set to be 0.3 by default. For more details, please refer to https://github.com/rujinwang/SCOPE/blob/master/R/perform_qc.R

Thanks. 
Rujin

**Comment by yifnzhao** [comment]
Thanks Rujin. I will give it a try.
