### ISSUE TITLE
CNV result

### ISSUE THREAD

**Issue by verne91** [rujinwang/SCOPE#13]
Hello,

How can I get the CNV result from the `iCN_sim` variable in the section 3.4 in the vignette?
I see the columns are the cell, how to get the exact coordinate from the rows?

In addition, if I have 1,000 cells, do I need to set `T=1:1000` in the `normalize_scope_foreach` function?
what is the input cell order when I assign the groups/clones in `initialize_ploidy_group` function?

Thank you!

**Comment by rujinwang** [comment]
Hi @verne91 
Thanks for your interest in SCOPE. 

> How can I get the CNV result from the iCN_sim variable in the section 3.4 in the vignette?

Please run through every steps by section. `iCN_sim` is generated in section 3.3. 

> how to get the exact coordinate from the rows?

Please refer to `ref_sim`

> do I need to set T=1:1000 in the normalize_scope_foreach function?

No. `T` is a vector of integers indicating number of CNV groups, not the number of total cells. 

> what is the input cell order when I assign the groups/clones in initialize_ploidy_group function?

The order is the same as `Y` column. 

Best, 
Rujin

**Comment by verne91** [comment]
Thank you!

sorry for the typo. Yes, `iCN_sim` is generated from section 3.3.
Can I just combine the coordinates from `ref_sim` into `iCN_sim` to get the CNV calls?

In addition, how to determine the parameter `T`? I don't know the number of CNV groups from the data.

**Comment by verne91** [comment]
Also, may I please know which parameter to control the number of cells? I use the same code in the vignette, and only change the input folder. I have 1000 cells but the output is still 5 cells. 
Thanks!

**Comment by rujinwang** [comment]
Hi @verne91 

> Can I just combine the coordinates from ref_sim into iCN_sim to get the CNV calls?

Not sure I understand correctly. You can get CNV calls from `iCN` matrix.

> how to determine the parameter T?
 
We usually set `T=1:5` or `T=1:7`

**Comment by rujinwang** [comment]
> Also, may I please know which parameter to control the number of cells? I use the same code in the vignette, and only change the input folder. I have 1000 cells but the output is still 5 cells.
> Thanks!

Please check the dimension of your `Y` matrix and make sure you are not using the toy example data

**Comment by verne91** [comment]
Yes, I see the `iCN` matrix is the calls, but it does not include the coordinates.
I mean are the coordinates in the `ref_sim` exactly same with that in the `iCN` matrix?

My `Y` matrix has 1000 columns, but `iCN` only has 5 columns.

**Comment by rujinwang** [comment]
> Yes, I see the `iCN` matrix is the calls, but it does not include the coordinates. I mean are the coordinates in the `ref_sim` exactly same with that in the `iCN` matrix?
> 
> My `Y` matrix has 1000 columns, but `iCN` only has 5 columns.

Please use `ref` generated from `ref <- qcObj$ref`. I think `ref_sim` is from the simulated or toy data. You can check if the dimension of `Y` matches with `ref_sim`. If yes, the coordinates are exactly the same.

Please make sure you have the correct input for `segment_CBScs()`. You need to specify your own `Y = Y`, not using `Y = Y_sim`.

**Comment by verne91** [comment]
That's all right. I think all the `Y_sim` and `ref_sim` in the 3rd section in vignette should be `Y` and `ref` if I want to use my own data.

In section 3.2, there is a variable `clones` with 5 elements. Is the size of `clones` equal to the sample size?
If so, how can I know if each sample is tumor or normal?

**Comment by rujinwang** [comment]
`clones` indicates the clonal membership for each cell. The length of `clones` is equivalent to `ncol(Y)`. If you have the cell labels as prior knowledge, use that to specify `clones`. Otherwise use the Gini coefficients to identify normal cells.
