### ISSUE TITLE
"Yhat.noK.sim" and "beta.hat.noK.sim" don't exist

### ISSUE THREAD

**Issue by sanghoonleeeins** [rujinwang/SCOPE#15]
Hi, 

I am running SCOPE following the vignette code. While running SCOPE, I found that "Yhat.noK.sim" and "beta.hat.noK.sim" don't exist.  In the "3.2 Running SCOPE with negative control samples," please see the code below.  "Yhat.noK.sim" and "beta.hat.noK.sim" haven't been made, but I don't understand where they are coming from?  Could you give some explanation? 

### Group-wise ploidy initialization
clones <- c("normal", "tumor1", "normal", "tumor1", "tumor1")
ploidy.sim.group <- initialize_ploidy_group(Y = Y_sim, Yhat = **Yhat.noK.sim**,
                                ref = ref_sim, groups = clones)
ploidy.sim.group

### Group-wise normalization
normObj.scope.sim.group <- normalize_scope_group(Y_qc = Y_sim,
                                    gc_qc = ref_sim$gc,
                                    K = 1, ploidyInt = ploidy.sim.group,
                                    norm_index = which(clones=="normal"),
                                    groups = clones,
                                    T = 1:5,
                                    beta0 = **beta.hat.noK.sim**)
 

Thank you, 
Sanghoon

**Comment by rujinwang** [comment]
Hi @sanghoonleeeins, 
Thanks for your interest in SCOPE. 
Both `Yhat.noK.sim` and `beta.hat.noK.sim` are from the first-pass CODEX2 run without latent factors. That is to say, `Yhat.noK.sim=normObj.sim$Yhat` and `beta.hat.noK.sim=normObj.sim$beta.hat`. 

Best, 
Rujin

**Comment by sanghoonleeeins** [comment]
Thank you for your explanation! I tested it and it works.
