### ISSUE TITLE
question about pre-stored hg19 and hg38 bed file

### ISSUE THREAD

**Issue by xikanfeng2** [rujinwang/SCOPE#2]
I noticed the start position of each chromosome in the bed file  is not 0. I am wondering how to determine the start position of each chromosome.

**Comment by xikanfeng2** [comment]
Do you remove the N values at the head of each chromosome and start from the position of non-N values?

**Comment by xikanfeng2** [comment]
Also for the end position, it is not same as the end position displayed in ucsc(http://hgdownload.cse.ucsc.edu/goldenPath/hg19/bigZips/hg19.chrom.sizes). How to determine it?

**Comment by rujinwang** [comment]
Hi, 
Thanks for bringing this up. Package is updated now. The coordinates are obtained from the reference genome (e.g., the BSgenome.Hsapiens.UCSC.hg38/BSgenome.Hsapiens.UCSC.hg19 packages).
