### ISSUE TITLE
errors when running scope

### ISSUE THREAD

**Issue by xikanfeng2** [rujinwang/SCOPE#4]
errors reported when running scope. Error information is as follows:
```Rscript
There are 90 samples and 4960 bins after QC step.
Computing normalization with no latent factors
Iteration 1     beta diff =0.00992      f(GC) diff =4.16e-08
Iteration 2     beta diff =8.65e-06     f(GC) diff =5.53e-13
Stop at Iteration 2.
Initialization ...
Error in { : task 1 failed - "invalid 'x'"
Calls: normalize_scope_foreach -> getfGC_foreach -> %dopar% -> <Anonymous>
停止执行
```

**Comment by rujinwang** [comment]
Hi, 
Thanks for your interest in SCOPE!
I can hardly tell what's causing theses errors. Could you please share a toy dataset with me that can help me debug? Thanks!

Rujin

**Comment by MinBio** [comment]
Hi Rujin,
I got the same error when running normalize_scope_foreach step.  Do you have any solutions? 
![Screenshot 2020-03-18 23 59 44](https://user-images.githubusercontent.com/26354783/77033357-012c6c00-6975-11ea-833a-68bafcf91430.png)

**Comment by rujinwang** [comment]
Hi @MinBio , 
Thank you for your interest in SCOPE! Is it possible for you to share a toy data with me to help fix this bug? I never have this error while running my own code. 

Best, 
Rujin

**Comment by rujinwang** [comment]
This bug arose from a cell which failed to meet the minimum coverage requirement in the following analysis. perform_qc() has been updated.
