### ISSUE TITLE
dim(X) length error when dealing with single control sample

### ISSUE THREAD

**Issue by KEYS248** [rujinwang/SCOPE#5]
Hello SCOPE contributors! I'm very excited to utilize this tool, I think it has great potential. Thank you for all the work you put into this project :)

Currently working through with some of my own data, I've narrowed down a particular problem in the `normalize_scope*.R()` functions. I believe this error is actually caused for the same reason as issue #3. I'm currently using R version 3.6.3 so I'm not sure if this problem exists in the R 4.0 preview version which you may be developing this in. I believe this error only occurs if you have a single control sample. When filtering the Y_qc matrix, if you are only dealing with a single column (in the case of having a single control sample), a line like 173 `betahatnew <- apply((Y_qc/(fhatnew * Nmat * exp(ghat %*%t(hhat))))[, norm_index], 1, median)` changes the matrix to be a vector and vectors don't work for `apply()` functions. [Stackoverflow reference](https://stackoverflow.com/questions/10737452/prevent-automatic-conversion-of-single-column-to-vector/10737525)

This fix is simple, just add `, drop = FALSE` to the matrix filtering as you have done at other places of your script. That would look like `betahatnew <- apply((Y_qc/(fhatnew * Nmat * exp(ghat %*%t(hhat))))[, norm_index, drop = FALSE], 1, median)`. When I modify the code to incorporate this, it works for me with a single control sample.

Error message:
```
> normObj.test <- normalize_scope(Y_qc = Y_test, K = 1, T = 1:length(sampname_raw),
+                                         gc_qc = gc_test,beta0 = beta.hat.noK.test,ploidyInt = ploidy.test,
+                                         norm_index = which(Gini<=0.12))
Initialization ...
1 	2 	Computing normalization with k = 1 latent factors ...
k = 1
Error in apply((Y_qc/(fhatnew * Nmat * exp(ghat %*% t(hhat))))[, norm_index],  : 
  dim(X) must have a positive length
```

**Comment by rujinwang** [comment]
Hi @KEYS248 
Yes, you are correct. Thanks for letting me know this defect. Have updated the package. Appreciate your suggestions!

Best, 
Rujin
