### ISSUE TITLE
error with function perform_qc(), dim(X) must have a positive length

### ISSUE THREAD

**Issue by edouard-couv** [rujinwang/SCOPE#8]
Hi,

I am currently trying to use  SCYN (which calls SCOPE) on 3 different 10X CNV batch. It worked perfectly fine for the two first ones but not for the last one. I ran my script using the python function “scyn_operator.call(bam_dir, output_dir)” which calls SCOPE. The difference between my three batches is the number of cells. The first two have 298 and 533 cells and the last one which does not work has 1171 cells. Here is the error of message from R for the last batch:

> qcObj <- perform_qc(Y_raw = Y_raw, sampname_raw = sampname_raw, ref_raw = ref_raw, QCmetric_raw = QCmetric_raw)
Removed 0 samples due to failed library preparation.
Removed 0 samples due to low proportion of mapped reads.
Excluded 371 bins due to extreme GC content.
Excluded 353 bins due to low mappability.
Error in apply(apply(Y.nonzero, 2, function(x) { : 
  dim(X) must have a positive length

I split the problematic batch in 4 groups using the first letter of the barcode as group (so A, C, G and T) and ran the same script on those 4 smaller groups and the scripts ran without any problems.
Do you have any ideas why I have this issue?

Best,
Edouard Couvreu 

Here is my info session
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] WGSmapp_0.99.6                    SCOPE_0.99.13                     BSgenome.Hsapiens.UCSC.hg19_1.4.0
 [4] BSgenome_1.54.0                   rtracklayer_1.46.0                Rsamtools_2.2.3                  
 [7] Biostrings_2.54.0                 XVector_0.26.0                    GenomicRanges_1.38.0

**Comment by rujinwang** [comment]
Hi @edouard-couv , 
Thanks for your interest in SCOPE. 
I never used SCYN before so I'm not quite sure why it works after your split into smaller group for the problematic batch. Did you try to follow the SCOPE vignette and use the standalone SCOPE package?
For the error that you had, I think it's about the dimension of your post-QC input. I would suggest trying the standalone R package. For this QC step, it won't take long.

Best, 
Rujin

**Comment by edouard-couv** [comment]
I tried running only it with SCOPE and it was not working with all the cells in the same run and was working when split in four. However, I tried again and it worked. I do not know what changed, I checked my two sessions and no differences can explain why it was not working but now it works.
Thanks for your fast response,

Edouard
