### ISSUE TITLE
Runtime of segmentation

### ISSUE THREAD

**Issue by pedrofale** [rujinwang/SCOPE#9]
I am trying to run SCOPE on simulated data, and I am struggling to get results in reasonable time. I have 400 cells and read counts spanning across 10k genomic bins, and after 20 hours SCOPE has only arrived to sample number 4 (as indicated by the log message "Calculating scan statistic for sample 4: .". The previous steps finish in about 4 hours, which seems okay.

According to Table S4 of the SCOPE manuscript, 30 minutes for the segmentation step should be more than enough for my data set, since that's about the time reported for the Breast Tissue nuclei section E from 10X Genomics. What is going on? I am using the same commands as in the tutorial in the R vignette for SCOPE, and I am running SCOPE in a HPC cluster using 10 compute nodes.

How can I make the segmentation run faster?

**Comment by rujinwang** [comment]
Hi @pedrofale , 
Thanks for your interest in SCOPE. 
This is weird. What is the bin resolution did you use? Did you try parallel computing? We recommend segmenting chromosomes in parallel. The numbers in Table S4 are reported by parallelized processing. You can submit jobs for different chromosomes simultaneously. 

Best,
Rujin

**Comment by pedrofale** [comment]
Thanks for the reply! 

This is simulated data. I understand I can split the genome into "chromosomes", but 10k bins already seems comparable to the number of bins of each chromosome in the Breast Tissue nuclei section E from 10X Genomics, for which you indicate the segmentation takes about 30 minutes in Table S4. 

Is this related to the bin width that I set? I artificially set the bins to be of width 5 (for no particular reason) when constructing the "ref_sim" GRanges object. If I set larger widths, will it be faster? What number should I put there?

**Comment by rujinwang** [comment]
Hi @pedrofale 
I don't think so. SCOPE set bin size to be 500kb by default. In our paper, the total number of bins **along the whole genome** is approximately 5k. If you have 10k bins per chromosome, that's computationally extensive. 

Yes, it has something to do with the bin width you set. I would recommend setting a larger value. You can try the 500kb, which I believe is the default option in the function `get_bam_bed `. 

Rujin

**Comment by pedrofale** [comment]
Thank you Rujin, I aggregated bins to reduce the size of the data and it works now.
